"""Inline SVG diagrams.

Hand-authored rather than generated by a library, for the same reason the tool
vendors one dependency: these are eight shapes and some text, and a charting
library would be more code than the drawings.

Every diagram follows three rules:

  * Colour comes from CSS classes, never from fill attributes, so the diagrams
    and the stylesheet cannot drift apart — and the node colours are the same
    ones the terminal output uses, so a reader who learns "purple is a
    third-party API" in the legend keeps that knowledge in the scan output.
  * Text is set in absolute px inside a viewBox that scales. Below roughly
    46rem that text would fall under about 9px, so the wrapper scrolls
    horizontally at a floor width instead of shrinking into illegibility.
    A squinted diagram is worse than a scrolled one.
  * Each carries a <title> and a <desc> and is announced as an image, so a
    screen reader gets the claim the picture is making rather than silence.
"""

import hashlib
import html


def figure(svg, caption=None, min_width=None, cls=""):
    """Wrap a diagram: scroll container, optional caption."""
    style = f' style="min-width:{min_width}px"' if min_width else ""
    cap = f'<figcaption>{caption}</figcaption>' if caption else ""
    return (f'<figure class="dia {cls}">'
            f'<div class="dia-scroll"><div class="dia-inner"{style}>{svg}</div></div>'
            f'{cap}</figure>')


def _uid(text):
    """A stable id for a diagram's title and description.

    Python salts str.__hash__ per process, so building ids from hash() produced
    different HTML on every run — which meant the CI check that regenerating
    the site yields no diff would have failed every single time, for no reason
    anyone could see from the diff. Content-addressed and deterministic."""
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:8]


def _svg(w, h, title, desc, body, cls="dia-svg"):
    tid, did = "t" + _uid(title), "d" + _uid(desc)
    return (f'<svg class="{cls}" viewBox="0 0 {w} {h}" role="img" '
            f'aria-labelledby="{tid} {did}" '
            f'preserveAspectRatio="xMidYMid meet">'
            f'<title id="{tid}">{html.escape(title)}</title>'
            f'<desc id="{did}">{html.escape(desc)}</desc>'
            f'{body}</svg>')


def _box(x, y, w, h, label, cls="", sub=None, rx=5):
    """A labelled rounded box. Label is centred; optional second line."""
    t = (f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" class="n-box {cls}"/>')
    if sub:
        t += (f'<text x="{x + w/2}" y="{y + h/2 - 3}" class="n-label {cls}">{html.escape(label)}</text>'
              f'<text x="{x + w/2}" y="{y + h/2 + 11}" class="n-sub">{html.escape(sub)}</text>')
    else:
        t += f'<text x="{x + w/2}" y="{y + h/2 + 4}" class="n-label {cls}">{html.escape(label)}</text>'
    return t


def _edge(x1, y1, x2, y2, cls="e-line"):
    """A gently curved connector. Straight lines through a fan of eight edges
    read as a starburst; a slight bow keeps them separable."""
    mx = (x1 + x2) / 2
    return f'<path d="M{x1} {y1} C{mx} {y1}, {mx} {y2}, {x2} {y2}" class="{cls}"/>'


# ---------------------------------------------------------------------------
# Landing: the advantage
# ---------------------------------------------------------------------------

def blast_radius():
    """One vendor degrades. Which services are in it?

    This is the diagram that has to earn the page, because "why map
    dependencies" is answered by a question you cannot currently answer, not by
    a feature list. The highlight *is* the answer.

    Sized for the hero's art column (~480px), not for the full page width. The
    first version was 880 wide with four services and four dependencies, and it
    clipped its right-hand column inside the panel — a diagram whose punchline
    is cut off is worse than no diagram. Three and three makes the same point:
    two services are in it, one is not."""
    svc = [("checkout", 40, True), ("orders", 92, True), ("search", 144, False)]
    # Deliberately not colour-coded by kind: the only thing that should catch
    # the eye here is what broke and who is in it. Kind colours come later, in
    # the reach graph, where they carry the legend.
    dep = [("Stripe", 34, True), ("rds orders-prod", 96, False), ("s3 uploads", 158, False)]
    links = [(0, 0), (0, 1), (1, 0), (1, 2), (2, 2)]

    b = ['<g>']
    for si, di in links:
        hot = svc[si][2] and dep[di][2]
        b.append(_edge(150, svc[si][1] + 16, 270, dep[di][1] + 16,
                       "e-line e-hot" if hot else "e-line"))

    b.append('<text x="0" y="20" class="d-cap">YOUR SERVICES</text>')
    for name, y, hot in svc:
        b.append(_box(0, y, 150, 32, name, "hit" if hot else ""))

    b.append('<text x="270" y="20" class="d-cap">WHAT THEY REACH</text>')
    for name, y, down in dep:
        b.append(_box(270, y, 190, 32, name, "down" if down else ""))
    b.append('<circle cx="446" cy="50" r="4" class="pulse"/>')
    b.append('<text x="470" y="44" class="d-note">degraded</text>')

    b.append('<line x1="0" y1="214" x2="560" y2="214" class="d-rule"/>')
    b.append('<text x="0" y="240" class="d-ask">Stripe is degraded. Who is in it?</text>')
    b.append('<text x="0" y="264" class="d-ans">checkout and orders. Not search.</text>')
    b.append('</g>')

    return figure(
        _svg(560, 276,
             "Blast radius of one degraded dependency",
             "Three services on the left connect to three shared dependencies on the right. "
             "Stripe is marked degraded; the edges from checkout and orders to Stripe are "
             "highlighted, showing those two services are affected and search is not.",
             "".join(b)),
        min_width=460)


def payoff_icon(name):
    """20px line icons for the payoff cards. currentColor throughout."""
    paths = {
        # incident / alert
        "incident": '<path d="M10 3.5 18.5 17H1.5L10 3.5Z"/><path d="M10 8.5v3.5"/><circle cx="10" cy="14.6" r=".9" class="i-dot"/>',
        # change review / branch
        "change": '<circle cx="5.5" cy="4.5" r="2"/><circle cx="5.5" cy="15.5" r="2"/><circle cx="14.5" cy="4.5" r="2"/><path d="M5.5 6.5v7"/><path d="M14.5 6.5c0 4-9 2.5-9 7"/>',
        # compliance / shield
        "compliance": '<path d="M10 2.5 16.5 5v5.2c0 3.6-2.6 6.2-6.5 7.3-3.9-1.1-6.5-3.7-6.5-7.3V5L10 2.5Z"/><path d="M7.2 10.1 9.3 12.2l3.6-3.8"/>',
        # migration / arrows
        "migration": '<path d="M2.5 6.5h11"/><path d="M10.5 3.5 13.8 6.5 10.5 9.5"/><path d="M17.5 13.5h-11"/><path d="M9.5 10.5 6.2 13.5 9.5 16.5"/>',
    }
    return (f'<svg class="p-icon" viewBox="0 0 20 20" fill="none" stroke="currentColor" '
            f'stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" '
            f'aria-hidden="true">{paths[name]}</svg>')


# ---------------------------------------------------------------------------
# Landing / docs: what a scan produces, and what the colours mean
# ---------------------------------------------------------------------------

def reach_graph():
    """The graph a scan produces, colour-keyed to the terminal output.

    Doubles as the legend for the scan output above it — which is the point.
    Before this, a visitor met coloured [cloud] and [opaque] tags with no key."""
    targets = [
        ("aws rds ingestor-db", 14, "cloud", "database"),
        ("aws sqs events-inbound", 62, "cloud", "queue"),
        ("gcp sql analytics-primary", 110, "cloud", "database"),
        ("Stripe", 158, "ext", "third-party API"),
        ("HashiCorp Vault", 206, "ext", "third-party API"),
        ("iam-role platform-ingestor", 254, "ident", "cloud identity"),
        ("secret ingestor-api-creds", 302, "opaque", "target unknown"),
    ]
    b = ['<g>']
    for _, y, kind, _ in targets:
        b.append(_edge(264, 176, 392, y + 17, f"e-line e-{kind}"))
    b.append(_box(24, 158, 240, 36, "platform/ingestor", "workload", rx=5))
    b.append('<text x="24" y="146" class="d-cap">WORKLOAD</text>')
    b.append('<text x="392" y="10" class="d-cap">WHAT IT REACHES</text>')
    for name, y, kind, sub in targets:
        b.append(_box(392, y, 300, 36, name, kind, sub=sub))
    b.append('</g>')
    return figure(
        _svg(720, 350,
             "The reach graph a scan produces",
             "The workload platform/ingestor on the left, connected to seven targets on the "
             "right: three cloud resources, two third-party APIs, one cloud identity, and one "
             "unresolved secret reference. Each target is coloured by kind.",
             "".join(b)),
        min_width=660)


def legend_rows():
    """The legend's rows, without the wrapper, for callers that want to set
    their own layout (two columns under a full-width graph, say)."""
    return _legend_items()


def legend():
    """A plain HTML legend — it is a list of terms, not a picture, and building
    it as HTML keeps it selectable, wrappable and readable on a phone."""
    items = [
        ("cloud", "[cloud]", "A named cloud resource — an RDS instance, a queue, a bucket"),
        ("ext", "[external]", "A third-party API outside your estate"),
        ("ident", "[identity]", "A cloud role or service account the workload assumes"),
        ("opaque", "[opaque]", "A dependency that exists but whose target is in a Secret"),
        ("svc", "[service]", "Another service inside the cluster"),
    ]
    return f'<div class="legend">{_legend_items()}</div>'


def _legend_items():
    items = [
        ("cloud", "[cloud]", "A named cloud resource — an RDS instance, a queue, a bucket"),
        ("ext", "[external]", "A third-party API outside your estate"),
        ("ident", "[identity]", "A cloud role or service account the workload assumes"),
        ("opaque", "[opaque]", "A dependency that exists but whose target is in a Secret"),
        ("svc", "[service]", "Another service inside the cluster"),
    ]
    return "".join(
        f'<div class="lg-row"><span class="lg-swatch lg-{k}"></span>'
        f'<code class="lg-tag">{html.escape(tag)}</code>'
        f'<span class="lg-desc">{html.escape(desc)}</span></div>'
        for k, tag, desc in items)


# ---------------------------------------------------------------------------
# Landing / docs: the pipeline
# ---------------------------------------------------------------------------

def pipeline():
    b = ['<g>']
    cols = [
        (20, "READS", [("./manifests", "a directory of YAML"),
                       ("stdin", "helm template | reachmap"),
                       ("@cluster", "live objects via kubectl")]),
        (330, "RESOLVES", [("16 detectors", "env, args, mesh, KEDA, CRs…"),
                           ("parsers", "ARN, DSN, in-cluster DNS"),
                           ("142 catalog rules", "hostname → named resource")]),
        (640, "EMITS", [("text · json", "read it, or feed it forward"),
                        ("mermaid · dot", "a diagram"),
                        ("sarif · backstage", "what CI already reads")]),
    ]
    for x, cap, items in cols:
        b.append(f'<text x="{x}" y="14" class="d-cap">{cap}</text>')
        for i, (name, sub) in enumerate(items):
            y = 30 + i * 58
            b.append(_box(x, y, 240, 46, name, "stage", sub=sub))
    for y in (53, 111, 169):
        b.append(f'<path d="M272 {y} H322" class="e-line e-arrow" marker-end="url(#rm-arrow)"/>')
        b.append(f'<path d="M582 {y} H632" class="e-line e-arrow" marker-end="url(#rm-arrow)"/>')
    b.append('</g>')
    defs = ('<defs><marker id="rm-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" '
            'markerHeight="6" orient="auto"><path d="M0 1 L7 4 L0 7" class="e-head"/></marker></defs>')
    return figure(
        _svg(900, 200,
             "How a scan flows",
             "Three stages. Reads: a manifest directory, stdin, or a live cluster. Resolves: "
             "sixteen detectors, the ARN and DSN parsers, and 142 catalog rules. Emits: text "
             "and JSON, Mermaid and DOT diagrams, SARIF and Backstage entities.",
             defs + "".join(b)),
        min_width=810)


def confidence_scale():
    """Three chips, not three bars.

    The first cut drew bars of decreasing length. That is a quantity, and the
    paragraph above the diagram says in as many words that confidence is a
    bucket and not a number — the picture was arguing with the text. Equal
    chips say "three named categories", which is the actual claim."""
    rows = [
        ("confirmed", "conf", "The manifest names the target outright",
         "a literal ARN, an ExternalName, a proxy argument, a StorageClass provisioner"),
        ("likely", "likely", "Parsed from config and matched to a catalog rule",
         "a hostname the catalog recognises, or a shared-credential join"),
        ("possible", "poss", "Something is there, but nothing names it",
         "an endpoint no rule recognises, or a target inside a Secret"),
    ]
    b = ['<g>']
    for i, (name, cls, claim, eg) in enumerate(rows):
        y = 6 + i * 62
        b.append(f'<rect x="0" y="{y + 6}" width="12" height="12" rx="3" class="cf-chip cf-{cls}"/>')
        b.append(f'<text x="24" y="{y + 17}" class="cf-name cf-{cls}">{name}</text>')
        b.append(f'<text x="150" y="{y + 17}" class="cf-claim">{html.escape(claim)}</text>')
        b.append(f'<text x="150" y="{y + 36}" class="cf-eg">{html.escape(eg)}</text>')
        if i < 2:
            b.append(f'<line x1="0" y1="{y + 50}" x2="700" y2="{y + 50}" class="d-rule"/>')
    b.append('</g>')
    return figure(
        _svg(700, 192,
             "The three confidence buckets",
             "Confirmed: the manifest names the target outright. Likely: parsed from config "
             "and matched to a catalog rule. Possible: something is there but nothing names it.",
             "".join(b)),
        min_width=600)


# ---------------------------------------------------------------------------
# Docs diagrams
# ---------------------------------------------------------------------------

def detector_surfaces():
    """Where the detectors actually read from. The point of the picture is that
    most of these surfaces are not the pod spec."""
    ring = [
        ("container env, args", 20, 16, "in"),
        ("ConfigMap contents", 20, 74, "in"),
        ("mounted Secrets", 20, 132, "in"),
        ("image reference", 20, 190, "in"),
        ("ServiceAccount annotations", 500, 16, "out"),
        ("KEDA triggers", 500, 74, "out"),
        ("mesh + egress policy", 500, 132, "out"),
        ("cloud resource CRs", 500, 190, "out"),
    ]
    b = ['<g>']
    for _, x, y, side in ring:
        if side == "in":
            b.append(_edge(240, y + 16, 300, 120, "e-line"))
        else:
            b.append(_edge(500, y + 16, 440, 120, "e-line"))
    b.append(_box(300, 102, 140, 40, "workload", "wl"))
    for name, x, y, side in ring:
        b.append(_box(x, y, 220, 32, name, "surf" + (" surf-out" if side == "out" else "")))
    b.append('<text x="20" y="252" class="d-cap">IN THE POD SPEC</text>')
    b.append('<text x="500" y="252" class="d-cap">EVERYWHERE ELSE</text>')
    b.append('</g>')
    return figure(
        _svg(740, 266,
             "Where detectors read from",
             "Eight surfaces feed one workload. Four are inside the pod spec: container env "
             "and args, ConfigMap contents, mounted Secrets, and the image reference. Four "
             "are outside it: ServiceAccount annotations, KEDA triggers, mesh and egress "
             "policy, and cloud resource custom resources.",
             "".join(b)),
        min_width=680,
        cls="dia-wide")


def gate_flow():
    """Vertical, not horizontal.

    The first cut was a 890px-wide left-to-right flow, which is fine on the
    landing page and wrong here: the docs column is about 700px, so it scrolled
    on every screen. A diagram the reader has to drag is a diagram they skip."""
    b = ['<g>',
         '<defs><marker id="rm-arrow2" viewBox="0 0 8 8" refX="6.5" refY="4" markerWidth="5" '
         'markerHeight="5" orient="auto"><path d="M0.5 1 L6.5 4 L0.5 7 Z" class="e-head"/></marker></defs>']
    b.append(_box(70, 14, 250, 42, "graph on main", "stage", sub="the base"))
    b.append(_box(380, 14, 250, 42, "graph on the branch", "stage", sub="the head"))
    b.append('<path d="M195 58 C195 78, 350 70, 350 92" class="e-line e-arrow" marker-end="url(#rm-arrow2)"/>')
    b.append('<path d="M505 58 C505 78, 350 70, 350 92" class="e-line e-arrow" marker-end="url(#rm-arrow2)"/>')
    b.append(_box(225, 96, 250, 42, "diff", "stage", sub="matched on (from, to, relation)"))
    b.append('<path d="M350 140 V174" class="e-line e-arrow" marker-end="url(#rm-arrow2)"/>')
    b.append(_box(225, 178, 250, 42, "gates", "stage", sub="added edges only"))
    outs = [("comment on the PR", 10, "ok"), ("SARIF to security tab", 245, "ok"),
            ("exit 3 — build fails", 480, "down")]
    for name, x, cls in outs:
        b.append(f'<path d="M350 222 C350 244, {x + 105} 236, {x + 105} 258" '
                 f'class="e-line e-arrow" marker-end="url(#rm-arrow2)"/>')
        b.append(_box(x, 262, 210, 34, name, cls))
    b.append('</g>')
    return figure(
        _svg(700, 306,
             "How the pull-request gate runs",
             "The graph on main and the graph on the branch feed a diff, matched on from, to "
             "and relation. Gates evaluate added edges only, producing three outcomes: a "
             "comment on the pull request, SARIF for the security tab, and exit code 3 when "
             "a gate trips.",
             "".join(b)),
        min_width=640)


def secrets_boundary():
    """What cluster mode reads, and the one thing it does not.

    Stacked rather than side by side, for the same reason as the gate flow: this
    lives in a 700px column."""
    b = ['<g>']
    b.append('<rect x="0" y="16" width="700" height="140" rx="7" class="zone"/>')
    b.append('<text x="18" y="38" class="d-cap">REACHMAP READS</text>')
    reads = [("Deployments, Services, ConfigMaps", 18, 48), ("ServiceAccounts, PVCs, StorageClasses", 356, 48),
             ("Istio, Gateway API, Cilium policy", 18, 82), ("KEDA ScaledObjects", 356, 82),
             ("ExternalSecret, SecretStore, SecretProviderClass", 18, 116)]
    for label, x, y in reads:
        w = 326 if x == 18 and y != 116 else (326 if x == 356 else 664)
        b.append(_box(x, y, w, 28, label, "read", rx=4))

    b.append('<path d="M350 158 V186" class="e-line e-cut"/>')
    b.append('<path d="M340 164 L360 180 M360 164 L340 180" class="e-cross"/>')

    b.append('<rect x="0" y="190" width="700" height="112" rx="7" class="zone zone-off"/>')
    b.append('<text x="18" y="212" class="d-cap">NEVER REQUESTED</text>')
    b.append(_box(18, 222, 300, 44, "Secret", "never", sub="not listed, not read, not cached"))
    b.append('<text x="342" y="238" class="z-note">A dependency mapper that pulls plaintext</text>')
    b.append('<text x="342" y="256" class="z-note">credentials out of a production cluster is</text>')
    b.append('<text x="342" y="274" class="z-note">a different and far more dangerous tool.</text>')
    b.append('<text x="342" y="294" class="z-note z-test">A test enforces this.</text>')
    b.append('</g>')
    return figure(
        _svg(700, 312,
             "What cluster mode reads, and what it never requests",
             "Above the line, the object kinds Reachmap lists from a cluster: workloads, "
             "services, config, service accounts, storage, mesh and egress policy, KEDA "
             "objects, and the External Secrets objects that describe Secrets. Below, crossed "
             "out: Secret objects themselves, which are never listed, read or cached.",
             "".join(b)),
        min_width=640)


def pr_comment_mock(table_rows):
    """The comment Reachmap leaves, drawn in HTML rather than SVG so the text
    stays selectable and reflows. Deliberately generic chrome — this illustrates
    our own output, and dressing it up as a specific vendor's UI would be a
    different and worse thing to do."""
    return f"""<div class="pr-mock" aria-label="Illustration of the pull-request comment Reachmap leaves">
  <div class="pr-head">
    <span class="pr-avatar" aria-hidden="true">R</span>
    <span class="pr-who">reachmap</span>
    <span class="pr-when">commented on your pull request</span>
  </div>
  <div class="pr-body">
    <p class="pr-title">Reachmap</p>
    <div class="pr-warn">
      <strong>This change trips a dependency gate on 1 new dependency.</strong>
      <div><code>shop/orders</code> &rarr; <strong>api.riskscore.io</strong> &mdash; new external API dependency</div>
    </div>
    <p class="pr-sub"><strong>1 new dependency</strong></p>
    {table_rows}
  </div>
</div>"""
